edges-collab/edges-io

- src/edges_io/io.py
> Fix hours in spec/resistance

- CHANGELOG.rst
- src/edges_io/__init__.py
- src/edges_io/data/__init__.py
- src/edges_io/data/antenna_simulators.toml
- src/edges_io/io.py
- src/edges_io/utils.py
Adds better support for Antenna Simulators.
Also adds ability to read Resistance metadata (fixes #7).
> Antenna simulators

- src/edges_io/io.py
Adds support for old resistance measurement formats. Takes the second column to be the relevant measurement (I could be wrong there).
> Old resistance compat

- src/edges_io/io.py
Convert kOhm to Ohm in old style thermistor files.
> Convert to Ohms

- src/edges_io/io.py
This should fix the problem, pending a test on actual files...
> Fix case where hot load was written in Ohms while others written in KOhm

- src/edges_io/io.py
- tests/test_io.py
> Io testing

- src/edges_io/h5.py
- src/edges_io/io.py
A few fixes related to the new HDF5 and incomplete observations PRs.
> fix: ensure optional H5 entries are treated optionally

- src/edges_io/io.py
- tests/test_io.py
Small fix due to the spectra being a list (of files) inside Spectra/
> fix: spectra run_num failed because spectra is a list

- .github/workflows/bump_version.yaml
- CHANGELOG.rst
- src/edges_io/cli.py
- src/edges_io/io.py
- src/edges_io/logging.py
- src/edges_io/utils.py
- tests/test_cli.py
- tests/test_io.py
This PR fixes some stuff about the logging. Primarily, it makes it so that the colored logging isn't turned on whenever edges-io is imported.
> fix logging

- src/edges_io/h5.py
- tests/test_h5object.py
Adds a few handy features to HDF5 file objects, including a `clear()` method
to flush all cached memory, and some better error reporting if validation
doesn't pass.
> hdf5 features

- .github/workflows/downstream_tests.yaml
- src/edges_io/h5.py
This makes it possible to not perform checks on the data when using `.from_data`.
> fix: don't always validate when doing from_data

- .github/workflows/test_suite.yaml
- README.rst
- docs/structure.rst
- example-obs-definition.yaml
- example-observation.yaml
- src/edges_io/h5.py
- src/edges_io/io.py
- tests/test_cli.py
- tests/test_h5object.py
- tests/test_io.py
This fixes the run_num <-> repeat_num issue, which is very important.
> Fix structure convert

- .github/workflows/bump_version.yaml
> fix: try again to get a push from the bump

- .github/workflows/bump_version.yaml
> ci: use persist-credentials=False

- src/edges_io/io.py
modified the float from kohm file to ensure it reads 'kohm' for each line
> Fix float from kohm

- src/edges_io/io.py
- src/edges_io/utils.py
Adds `receiverreading` and `switching_state` files to `list_of_files`.
> Fix list of files

- .isort.cfg
- .pre-commit-config.yaml
- setup.cfg
- src/edges_io/_structure.py
- src/edges_io/config.py
- src/edges_io/h5.py
- src/edges_io/io.py
- src/edges_io/utils.py
- tests/test_config.py
- tests/test_hickleable.py
- tests/test_io.py
BREAKING CHANGE: In the `CalibrationObservation`, there is no longer the
attributes `switching_state` and `receiver_reading` -- instead they are
plural, and are tuples of their respective objects.
> feat: ability to use multiple switching_states and receiver_readings

- src/edges_io/h5.py
- src/edges_io/io.py
Fixes the __getattr__ problem we're having.
> Fix-getattr

- .github/labels.yml
- .github/workflows/labeler.yml
> ci: fix labels

- .github/labels.yml
- docs/conf.py
- setup.cfg
Updates hickleable requirement to avoid bug in reloading hickle file objects.
> build: update hickleable requirement

- setup.cfg
- setup.py
Gets rid of setup.py and adds frozendict
> maint: add frozendict dep

- .github/workflows/test_suite.yaml
- pyproject.toml
- setup.cfg
- src/edges_io/io.py
- src/edges_io/io3.py
- src/edges_io/types.py
- src/edges_io/utils.py
**Summary**
Updates the requirements to numpy > 2, and fixes the decoding issue for np.genfromtxt.
**Checklist:** 
**Meta-info:**
> maint: require numpy>2

- src/edges_io/io.py
The code has the option to read gsh5 files it was just erroring out due to the file format check
> option to look for gsh5 files too
